version: '3.9'

services:
  boilerplate-frontend:
    container_name: boilerplate-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev
